const CONSTANTS = Object.freeze({
    MIN_PLAYERS: 2,

    MESSAGE_TYPE_KEY: 'MESSAGE_TYPE',
    MESSAGE_TYPE: {
        START_ROUND: 'STARTROUND',
        END_ROUND: 'ENDROUND',
        ROUND_INSTRUCTIONS: 'ROUNDINSTRUCTIONS',
    },

    ROUND_KEY: 'ROUND',
    ROUNDS: {
        LOBBY: 'LOBBY',
        HOST_ASKS_TEXT_PROMPT_TO_ALL: 'HOSTASKTEXTPROMPTTOALL',
        HOST_ASKS_RANK_PROMPT_TO_ALL: 'HOSTASKSRANKPROMPTTOALL',
        HOST_ASKS_MULTIPLE_CHOICE_PROMPT_TO_ALL: 'HOSTASKSMULTIPLECHOICEPROMPTTOALL',
        HOST_ASKS_MATCHING_PROMPT_TO_ALL: 'HOSTASKSMATCHINGPROMPTTOALL',
        PROMPT: 'PROMPT',
    },

    PROMPT_TYPE:{
        TEXT: "TEXT",
        RANK: "RANK",
        MULTIPLE_CHOICE: "MULTIPLECHOICE",
        MATCHING:'MATCHING',
    },

    DATA_KEY: 'DATA',

    TIME:{
        TO_ANSWER_PROMPT: 20000,
        TO_ANSWER_QUIZ: 10000,
    }
});

export default CONSTANTS;
