const CONSTANTS = Object.freeze({
    MIN_PLAYERS: 2,

    MESSAGE_TYPE_KEY: 'MESSAGE_TYPE',
    MESSAGE_TYPE: {
        START_ROUND: 'STARTROUND',
        END_ROUND: 'ENDROUND',
        ROUND_INSTRUCTIONS: 'ROUNDINSTRUCTIONS',
    },

    ROUND_KEY: 'ROUND',
    ROUNDS: {
        LOBBY: 'LOBBY',
        ASK_PLAYERS_QUESTION: 'ASKPLAYERSQUESTION',
        QUIZ_PLAYERS: 'QUIZPLAYERS',
    },

    DATA_KEY: 'DATA',

    TIME:{
        TO_ANSWER_PROMPT: 20000,
        TO_ANSWER_QUIZ: 10000,
    }
});

export default CONSTANTS;
